/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment2;

class AppTest {
    // @Test void appHasAGreeting() {
    //     App classUnderTest = new App();
    //     assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    // }
}
